# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1183, 681)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(4, -5, 1181, 681))
        self.bg.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.bg.setText("")
        self.bg.setObjectName("bg")
        self.bgborder = QtWidgets.QLabel(self.centralwidget)
        self.bgborder.setGeometry(QtCore.QRect(0, 0, 1181, 681))
        self.bgborder.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 2px Solid White")
        self.bgborder.setObjectName("bgborder")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1030, 620, 141, 51))
        self.pushButton.setStyleSheet("border: 1px Solid White;\n"
"color: rgb(255,255,255);\n"
"font: 14pt;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(890, 620, 141, 51))
        self.pushButton_2.setStyleSheet("border: 1px Solid White;\n"
"color: rgb(255,255,255);\n"
"font: 14pt;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gif = QtWidgets.QLabel(self.centralwidget)
        self.gif.setGeometry(QtCore.QRect(0, 0, 681, 411))
        self.gif.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 2px solid white;")
        self.gif.setText("")
        self.gif.setPixmap(QtGui.QPixmap("D:\jarvis\database\gui stuffs\Hero_Template.gif"))
        self.gif.setScaledContents(True)
        self.gif.setObjectName("gif")
        self.gif2 = QtWidgets.QLabel(self.centralwidget)
        self.gif2.setGeometry(QtCore.QRect(680, 0, 501, 411))
        self.gif2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 2px solid white;\n"
"")
        self.gif2.setText("")
        self.gif2.setPixmap(QtGui.QPixmap("D:\jarvis\database\gui stuffs\Earth.gif"))
        self.gif2.setScaledContents(True)
        self.gif2.setObjectName("gif2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(890, 520, 281, 91))
        self.textBrowser.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 75 16pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white")
        self.textBrowser.setObjectName("textBrowser")
        self.gif3 = QtWidgets.QLabel(self.centralwidget)
        self.gif3.setGeometry(QtCore.QRect(890, 415, 281, 101))
        self.gif3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border:2px solid white;")
        self.gif3.setText("")
        self.gif3.setPixmap(QtGui.QPixmap("D:\jarvis\database\gui stuffs\__02-____.gif"))
        self.gif3.setScaledContents(True)
        self.gif3.setObjectName("gif3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(4, 415, 881, 261))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 1px solid white")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\jarvis\database\gui stuffs\code_template.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bgborder.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "close"))
        self.pushButton_2.setText(_translate("MainWindow", "start"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:36pt; font-weight:72; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">time</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
